### ISSUE TITLE
lesbian

### ISSUE THREAD

**Issue by RRorg** [wooorm/alex#101]
`homosexual`:
> homosexual may be insensitive, use gay, gay man, **lesbian**, gay person/people instead

`lesbian`:
> Don’t use lesbian, it’s profane

**Comment by seanohue** [comment]
This raises the question -- what is the source for deciding if something is maybe insensitive vs. profane, etc.?

**Comment by RRorg** [comment]
I would go with the recommendations of well-established human rights organizations instead of trying to come up with my own ways:
The [Gay and Lesbian Alliance against Defamation](http://www.glaad.org/reference/offensive) does not see `lesbian` as an offensive term, and indeed supports it use as a noun, replacing the clinical term `homosexual`

**Comment by seanohue** [comment]
@RRorg That sounds like a good source to use. Should we try to find sources to include for other terms as well? That might be another issue. Perhaps there could even be a super-verbose flag to ask alex to cite its sources.

**Comment by wooorm** [comment]
There already is such a flag (`-w, --why`), but there aren’t many sources yet! 
Plus, glaad is [already used](https://github.com/wooorm/retext-equality/blob/master/script/lgbtq.yml), but please add more sources!

This issue in particular is caused by a mismatch between retext-profanitites and retext-equality. Thanks for noticing. I’ll deal with that somewhere soon this week!

**Comment by seanohue** [comment]
@wooorm Ah, thanks. I haven't had a chance to look at this project in depth but I'll try to find some time to contribute sources.

**Comment by wooorm** [comment]
I'd love that!
