### ISSUE TITLE
alex-slack: 

### ISSUE THREAD

**Issue by gpeden** [wooorm/alex#129]
The readme says: "alex ignores words meant literally, so “he”, He — ..., and the like are not warned about", but alex-slack is warning on 'him' and 'he':

![image](https://cloud.githubusercontent.com/assets/1175466/19006293/a21f77f8-8713-11e6-859d-5b3934458752.png)

Is this a bug? or do I need to configure things differently?
george

**Comment by wooorm** [comment]
Literal means [words in quotes, like those examples you used above](https://github.com/wooorm/nlcst-is-literal#isliteralparent-index), but your screenshots don’t show them.

**Comment by gpeden** [comment]
thanks for that explanation.  Is there a way to allow him / her without quotes?  Also, is there a way to add my own words to the exclusion / bad list?

**Comment by wooorm** [comment]
* You can allow certain cases through [several methods](https://github.com/wooorm/alex#ignoring-messages). These probably won’t work in the slack integration though, but that’s an issue for that repo.
* It’s not possible to add new patterns, either add them in [`retext-equality`](https://github.com/wooorm/retext-equality), [`retext-profanities`](https://github.com/wooorm/retext-profanities), or create something like those plugins and integrate them in your own system.

I’m closing this issue here as the original question is answered!
