### ISSUE TITLE
Online interpreter having issues with indentation

### ISSUE THREAD

**Issue by smileytechguy** [wooorm/alex#138]
A tab or 3 or more spaces at the beginning will cause nothing to be checked

Also, nothing inside quotes is checked either.

**Comment by wooorm** [comment]
It’s a feature, not a bug!

> A tab or 3 or more spaces at the beginning will cause nothing to be checked

That’s ’cause it’s markdown. The CLI and API both provide ways to turn that off.

> Also, nothing inside quotes is checked either.

That’s because quotes aren’t often something one can change, as they’re often meant literally, or said/written by someone else. Read more about that here: https://github.com/wooorm/alex#support

Thanks for the issue! Feel free to comment or raise new issues if you’ve got more questions.

**Comment by seanohue** [comment]
Should I submit a new issue for a feature request to check quotes?

**Comment by wooorm** [comment]
Sure!
