### ISSUE TITLE
Suicide-related terms

### ISSUE THREAD

**Issue by capitocapito** [wooorm/alex#38]
"Committed suicide" tends to be the norm when referring to the act, but it can have [broader negative connotations](https://www.psychology.org.au/Content.aspx?ID=5048). Maybe we should have Alex suggest newer phrasings such as "died by suicide." 

If approved, I can/would like to add the terms. (I'm getting my feet wet with Github.)

[More reading on Wikipedia](https://www.psychology.org.au/Content.aspx?ID=5048).

**Comment by JacksonGariety** [comment]
@capitocapito this is an interesting moral issue with many moving part.

Let's start from the position that a someone who dies by suicide is not a criminal and has not committed a crime. Rather, their death was the result of illness.

So we can say that they are a victim of depression. However, once someone is dead, they aren't anything. Rather, they simply are *not*. So we may call them a victim, but it wouldn't do any good once they're dead.

So the semantic issue must lie prior to the individual's death and therefore take the suicidal person into account. Psychoanalytically speaking, acts of suicide are negations of the ownership of the father, God, etc. So the goal of effectively preventing suicide is to make the person feel like they have someone watching over them, say, an authority figure.

The word victim certainly won't work since a victim has not been properly protected. A good authority figure has laws and rules, and so the most sensible thing to call a suicidal individual is "someone who is about to commit a crime against those who protect him/her." By identifying the authority figure one may save the persons life, and to assert authority requires punishment, which follows a crime, which must be **comitted.**

It's important to look at these GitHub tickets carefully. The future of the English language may depend upon it.

**Comment by JacksonGariety** [comment]
@capitocapito from your article:

*The word ‘commit’ is commonly used in connection with religious offences. Indeed suicide is considered wrong in many religions (Cholbi, 2009). Over time suicide has been regarded as a cardinal sin in some religions and is still often considered a moral sin.*

I think it important to recognize the role the concept of God plays in preventing suicide. Though I don't consider myself a Christian, I think it's safe to say that believing in the sacrifice of a corporeal God (Jesus, for instance) is by far the most effective way to prevent suicide. If we can imagine that God died on the cross, he did it intentionally and thus shows that he loves us and that, simultaneously, we are free. Love and freedom are the two tools by which we prevent suicide, be it by god or some other method, they must be included.

By omitting the religious references from the semantics of suicide, what results is the loss of belief in life itself.

**Comment by wooorm** [comment]
I’m fine with the addition. I’d like to help you create [your first PR](https://twitter.com/yourfirstpr). Are you experienced with node? Basically, you have to add the words to patterns in [retext-equality](https://github.com/wooorm/retext-equality/tree/master/script).

**Comment by capitocapito** [comment]
@wooorm I'm not very experienced, but I'm familiar and I get the basics. I'll add it soon. :)

**Comment by danielhickman** [comment]
I'm all for it since it's merely a warning. I think regardless of the right or religious stuff, it's nice to make sure you don't make it feel like a crime when someone it morning about it.

> Hey buddy, I'm sorry to hear John Doe commit suicide.

Sounds much worse than (in my opinion):
> Hey buddy, I'm sorry to hear John Doe completed suicide.

**Comment by wooorm** [comment]
@danielhickman Thanks for the feedback! Did you know that we are already working on a PR? wooorm/retext-equality#3

**Comment by danielhickman** [comment]
@wooorm Yup I saw it. I just wanted to add my two cents.

**Comment by wooorm** [comment]
Cool!

**Comment by rugk** [comment]
> Hey buddy, I'm sorry to hear John Doe completed suicide.

😧 Sorry, but this sounds horrible. Suicide is not something you should "complete". That's not a game you complete. More information here: http://www.speakingofsuicide.com/2013/04/13/language/

----

I hope you also know the so-called *Werther effect*, where there are also some [guidelines for journalists]((https://en.wikipedia.org/wiki/Copycat_suicide#Journalism_codes)) how to deal with suicides. From the wording perspective it is often recommend to not mention the word "suicide" at all - or at least not in the headline. I don't know whether this may also be included in Alex, but I wanted to be sure to mention it.

**Comment by capitocapito** [comment]
@rugk I think you're right. "Completed" should be on the opposite side, even per the original link posted in this issue. 

"Suicide" itself will throw a warning, although the reason is that it is "profane" (?). Not sure if that is the best categorization? I like the article's use of "stigmatizing" and wonder if that could be used in other places, too.

**Comment by wooorm** [comment]
Thanks for the feedback.

If you know have better suggestions, please create a pull request on **retext-equality** or **retext-profanity**, or both!

**Comment by rugk** [comment]
Okay: https://github.com/wooorm/retext-equality/pull/14
There I moved the "complete suicide" to the other site.
Anything else to do?

I found it in the equality file, so I doubt the reason for this to be shown is "profanity"...

**Comment by scivey** [comment]
@richardpetithory
