### ISSUE TITLE
Disappearing Issues

### ISSUE THREAD

**Issue by danielhickman** [wooorm/alex#43]
Type `he she` into the demo and you will receive `he` as an issue before you type `she` but finishing `she` makes both disappear. Is this because of `he/she`?
![image](https://cloud.githubusercontent.com/assets/5341898/9973469/3c3a9e50-5e28-11e5-8007-0a537602021e.png)

**Comment by wooorm** [comment]
@danielhickman I don’t think `he she` is actually used in real language, so I’m not sure that this is a bug?

The reason for this is that `or` patterns, as used internally by retext-equality, do not trigger a warning when occurring adjacent to each other ([optionally joined by `white-space` and `and` or `or`](https://github.com/wooorm/retext-equality/blob/e564c4ae22d68920c201972054226038f2b953fe/lib/equality.js#L459-L463)).

That is to say, this is design: a feature rather than a bug.

Please re-open this if you still have questions, or don’t agree :+1:

**Comment by danielhickman** [comment]
Oh okay that is a cool feature! I used he or she in testing my extension and thought it was a bug.

**Comment by wooorm** [comment]
Nah 😉
