### ISSUE TITLE
Vim Syntastic Plugin

### ISSUE THREAD

**Issue by chrisopedia** [wooorm/alex#44]
I'm trying to write a ViM [syntastic checker](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide) for Alex and running into some problems with the outputted format.  Is possible to adjust the output to make it friendlier for bash and vim?

My suggestion would would mean formatting it something more akin to this:

```bash
1:5-1:14  warning  `boogeyman` may be insensitive, use `boogey` instead
1:42-1:48  warning  `master` / `slaves` may be insensitive, use `primary` / `replica` instead
2:52-2:54  warning  `he` may be insensitive, use `they`, `it` instead
2:61-2:68  warning  `cripple` may be insensitive, use `person with a limp` instead
```

instead of this:

```bash

<stdin>
   1:5-1:14  warning  `boogeyman` may be insensitive, use `boogey` instead
  1:42-1:48  warning  `master` / `slaves` may be insensitive, use `primary` / `replica` instead
  2:52-2:54  warning  `he` may be insensitive, use `they`, `it` instead
  2:61-2:68  warning  `cripple` may be insensitive, use `person with a limp` instead

⚠ 4 warnings
```

**Note:** this means removing the first line and `<stdin>`, left aligning the warnings for easier parsing, and removing the line character and total warning count.

**Comment by sindresorhus** [comment]
I don't see why you need the output to change. You can just use a super simple regex: https://github.com/sindresorhus/SublimeLinter-contrib-alex/blob/8ef58610c816130794fde02e7be4cddb8d6ad089/linter.py#L21

**Comment by wooorm** [comment]
@chrisopedia I agree w/ @sindresorhus on this; and I’d rather not change how this works on the CLI (you can also use the API for more fine-grained control)

If that regex doesn’t do the trick, please re-open the issue.

P.S. AWESOME that you’re making a Vim plugin!

**Comment by lcd047** [comment]
The error format is unnecessarily complicated to parse (since the meaning of an error line depends on other lines before it), but it's perfectly usable.

There are however three problems that are show stoppers.

First, Vim's `system()` runs programs with `stdin` closed, and `alex` [doesn't expect that](https://github.com/wooorm/alex/blob/d9046a40e7338cb08159ea977bdb3e9b84a2d7cf/cli.js#L33):
```
$ alex example.md </dev/null

<stdin>: no issues found
```
Perhaps the presence of filenames on the command line should take precedence over the check for a TTY?

Second, `alex` is not an unique name for an executable.  There is a popular [lexer generator for Haskell](https://www.haskell.org/alex/) named the same, and running either `alex --version` and `alex` offer no indication that the program being run is actually `AlexJS` and not something else.  I suppose changing the output of `alex --version` to something like `AlexJS 1.2.0` would be a non-intrusive way to deal with that.

Third, `alex` is supposed to be able to check plain text files, but it really expects the files to be `markdown`.  This is a problem because lines indented with 4 spaces are ignored.  As far as I can tell there is no easy way to distinguish between `markdown` and plain text looking at contents alone, so maybe add a new option to skip `markdown pre-processing?

**Comment by sindresorhus** [comment]
> The error format is unnecessarily complicated to parse (since the meaning of an error line depends on other lines before it)

How exactly is it complicated? How does it depend on the line before it? It was straight forward for me to write a [regex](https://github.com/sindresorhus/SublimeLinter-contrib-alex/blob/8ef58610c816130794fde02e7be4cddb8d6ad089/linter.py#L21) for it. Literally took minutes. Syntastic might differ though.

> Perhaps the presence of filenames on the command line should take precedence over the check for a TTY?

:+1: That's how I usually do it.

> I suppose changing the output of alex --version to something like AlexJS 1.2.0 would be a non-intrusive way to deal with that.

:-1: `--version` should IMHO be a clean version. You can use `--help` for that.

**Comment by lcd047** [comment]
> How exactly is it complicated? How does it depend on the line before it?

The filenames.  When you see an error line
```
  1:40-1:46  warning  `master` / `slaves` may be insensitive, use `primary` / `replica` instead
```
you can't tell what file it refers to.  You have to keep track of filenames separately.  Not a _problem_, but still more complicated than it could have been.

> It was straight forward for me to write a regex for it. Literally took minutes. Syntastic might differ though.

Vim uses a `scanf()`-like system named `errorformat`.  In retrospect, things would have been a lot easier for everybody if syntastic used plain regexps instead, but the `errorformat` thing is what Vim offers out of the box for parsing errors, and I suppose it seemed fine at the time.

> `--version`  should IMHO be a clean version. You can use `--help` for that.

Whatever it is, it should provide a way to identify `AlexJS` uniquely.

**Comment by wooorm** [comment]
@lcd047 Thanks for the questions, interested in seeing it!

The error format is meant for humans, that’s why it focusses more on looking nice to humans instead of looking nice for computers. If @sindresorhus’s regex doesn’t do the trick, you could also write a script to interact with [alex(3)](https://github.com/wooorm/alex#api) directly instead of [alex(1)](https://github.com/wooorm/alex#command-line).

Also: Why would you want to pass multiple files through alex at once? I didn’t need that for atom-linter-alex; what exactly are you trying to do with Vim?

Your first point, sure #45.

Regarding your second point, alex is named `alex`, not `alexis`; more importantly, why are you running into this problem? I’m not sure where `alex` is, but I’d suggest instead of linking in PATH, to use some relative path to `node_modules/alex/cli.js`.

For your third point, maybe an option is indeed useful. However, as markdown is based on things people use in plain-text (such as strong with asterisks and code with ticks) too, I’m thinking it would do more harm than good to add such an option (my guess here is that you’ll have to check extensions and pass all files without a markdown extensions with this option).

**Comment by lcd047** [comment]
> If @sindresorhus’s regex doesn’t do the trick, you could also write a script to interact with alex(3) directly instead of alex(1)

Never mind, it's just a detail.  Error parsing already works fine.

> Also: Why would you want to pass multiple files through alex at once?

I don't, but Vim's error parsing insists on having a filename with each error.  If I can't get it from the output of a checker, I have to supply it some other way.  Like I said, it's a detail.

> Your first point, sure #45.

Thank you.

> Regarding your second point, `alex` is named `alex`, not `alexis`

I never said anything about an `alexis` (not intentionally anyway).

> more importantly, why are you running into this problem?

Because the Haskell package also has a binary named `alex`, and syntastic needs to make sure it has found the right one before enabling the corresponding checker.  Many Haskell developers that use syntastic have the other `alex` in their `$PATH`.  I suspect they would be confused if all of a sudden syntastic would try to run a lexer generator against random text files (and presumably failing with fanfare).

> However, as markdown is based on things people use in plain-text (such as strong with asterisks and code with ticks) too, I’m thinking it would do more harm than good to add such an option

My point is that tight now running `alex` against plain text file can ignore some lines, because they are indented with 4 spaces.  That happens regardless of file's extension, and it probably isn't what 
users expect.

> (my guess here is that you’ll have to check extensions and pass all files without a markdown extensions with this option).

That wouldn't be a problem for syntastic.  Vim already has a "filetype" associated to each file, and checkers are tied to these filetypes.  As I understand Sublime Text has a similar concept, I think they're called `selectors`.  Anyway, the user has to make sure the filetypes are set correctly, or a lot of other thing would start going wrong.

**Comment by wooorm** [comment]
> I never said anything about an alexis (not intentionally anyway).

Sorry, auto-correct, that should’ve been “alexjs” (with a J, hope it gets it right this time :wink:)

> Many Haskell developers that use syntastic have the other alex in their $PATH. I suspect they would be confused if all of a sudden syntastic would try to run a lexer generator against random text files (and presumably failing with fanfare).

I can imagine that would fail horribly haha, but, back to what I was trying to say, does *this* alex need to be in the `$PATH`? Is it necessary to look  in the `$PATH` for alex? Or, can you work around that and use a relative or absolute path?

**Comment by wooorm** [comment]
Whoops, commented too early. Your other points:

> My point is that right now running alex against plain text file can ignore some lines, because they are indented with 4 spaces.

I’m not sure if that’s really a “show stopper”, as you described earlier, how many people really have that in their documents? Anyway, I don’t really mind adding this in the future though, but I think markdown as a base is a really good default, even for most plain-text and other non-markdown files. I think I’m worried that you’re setting it as a default and I don’t think that that’s a wise approach!

**Comment by lcd047** [comment]
> does this alex need to be in the $PATH? Is it necessary to look in the $PATH for alex? Or, can you work around that and use a relative or absolute path?

It doesn't _have_ to be in the `$PATH`.  I could make the checker require users to set the absolute path.  But that would make it unlike the other 187 existing checkers.  As for trying to detect where `alex` lives outside of `$PATH`, I really don't want to go there.  Vim runs on a lot of OSes, from Commodore Amiga (should any of it still work in 2015), to VAX VMS, to the latest Mac OS-X, and each of these OSes have their standard directory structures.  Even though I'm pretty sure `alex` won't ever run on most of these systems, I'd still have to deal with low-level details most people run from.

> I think I’m worried that you’re setting it as a default and I don’t think that that’s a wise approach!

I'm not setting any default.  Vim distinguishes between text and `markdown` automatically, and when it guesses wrong the user has to fix the `filetype`.  Syntastic has different sets of checkers for `markdown` and for plain text.  They have nothing to do with one another, and when a program is set as a checker for several filetypes, the different instances can have different options.  `alex` as a checker for `markdown` would work, but `alex` as a checker for plain text files would miss some lines for no user-discernible reason, and people would complain about that to syntastic's maintainer.  On the other hand, I _could_ enable it as a checker only for `markdown`, and then people would complain that `alex` the program can check plain text files, and `alex` the checker can't.

**Comment by wooorm** [comment]
@lcd047 This probably stems from my unfamiliarity with Vim plug-ins, but can’t you install `alex` locally? It seems like what you’re trying to tell me is that `alex` must be installed by the user? Even if there’s a difference in file-structure across OSes, `node_modules/.bin/alex` still works right?

> Vim distinguishes between text and markdown automatically

Sorry, I didn’t get my point across clearly: I think that even plain-text benefits from being processed as plain-text, more so than it having a negative effect (through indented paragraphs)!

**Comment by lcd047** [comment]
I'm afraid the time I can afford to spend negotiating this is running out.  Thus, sadly, a checker for `alex` won't be part of syntastic.  Fortunately, such a checker (should anybody write a working one) can also be maintained [externally](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#external).  General directions for writing syntastic checkers are given in the relevant [wiki page](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide), and my thoughts on the OP's take on this can be found [here](https://github.com/scrooloose/syntastic/issues/1557).  Have a good day, everybody.
