### ISSUE TITLE
Profanities

### ISSUE THREAD

**Issue by wooorm** [wooorm/alex#46]
Currently, alex mostly checks for words which may or may not be deemed “inconsiderate” in certain contexts. I added racial terms a month ago, which started moving away from *possibly inconsiderate* to *clearly profane*.

Now, I’m thinking (and others have requested this too) of adding other [profanities](https://github.com/wooorm/profanities).

The best point _for_ this is that people (often not from the OSS community) expect alex to check these terms when they see the demo: “when something’s clearly insensitive, why does alex only warn about ‘he’” (paraphrased).

However, the downside of adding these aren’t used by people writing “real” text. I don’t think anyone will write “pancake face” in a thesis to describe people from Asian descent (https://github.com/wooorm/alex/issues/33#issuecomment-146069572).
In fact, having these terms in the module discourages people from both [using](https://github.com/wooorm/alex/issues/33#issuecomment-146069572) and working (source: private e-mail) on alex.

I’m not sure what to do; I’d like to hear your opinions :+1:

**Comment by yoshuawuyts** [comment]
I think it should catch profanities, possibly under a flag to start with. If we want to warn about possibly insensitive writing slurs are part of it.

**Comment by wooorm** [comment]
Thanks @yoshuawuyts!

Friendly ping: @sindresorhus, @pjf, @Charlotteis, would love your feedback on this :+1:

**Comment by alexgleason** [comment]
I mainly want this to make sure there's nothing insensitive in my source code written by other developers. Programmers are the more likely culprits than copywriters for this, and it's more easily obfuscated. (Related: #49)

**Comment by wooorm** [comment]
Thanks @alexgleason :+1:

**Comment by Charlotteis** [comment]
When you get a large project, contributed to by 10s-100s of developers you'll probably get something profane slipped in, maybe because they were frustrated at the time. See [twitter.com/gitlost](http://twitter.com/gitlost) for the sheer amount developers will swear in git commit messages alone :smile: 

Great point on the historical texts too.
I think @yoshuawuyts has the right idea with offering it under a flag, but I would also have no problem making it default behaviour. Maybe you could make it default but give a flag to turn off profanity warnings? Either way, at least it is in :)

**Comment by wooorm** [comment]
Thanks for the points @Charlotteis! :ok_hand:

**Comment by sindresorhus** [comment]
:+1: I think it's a good idea and should be on by default. Profanities are inconsiderate too. I want to ensure my docs to be profanity-free.

**Comment by pjf** [comment]
If profanity is a separate switch one can enable and disable, then I'm all for it. Features are great, and from the discussion thus far we'd have users that would find it useful.

If profanity checking isn't something the user can turn off, then I'm not a big fan. I *definitely* want alex to be able to find slurs and language that is offensive towards particular people, but neutral profanities are something I find much more acceptable, and a lot of people use them quite expressively. I *hope* to find people saying things are "ducking awesome" in my projects. :)

I'd be weakly inclined to have the option for alex to check for them off by default, as I feel they dilute alex's core purpose, which for me is to flag often *unintentionally* insensitive language. Profanities are almost always intentional, and neutral profanities especially so.

**Comment by wooorm** [comment]
Okay, sounds good. Thanks all for the feedback!

I’ll work on creating retext-profanity (probably based on [wooorm/profanities](https://github.com/wooorm/profanities)), externalised because it’s quite different from retext-equality.

Then, I’ll add support for a new flag to the CLI (`-p`, `--profanities`?) and an option to the API, to include profanities.

**Comment by Charlotteis** [comment]
`--profanities` is good because it's explicit. But you could alias `-p`. Use `--profanities` in the docs, but let people know they can use `-p` too? :)

**Comment by wooorm** [comment]
@Charlotteis Yeah I was indeed thinking of using both! :wink:
