### ISSUE TITLE
Suggestion: add "sane"

### ISSUE THREAD

**Issue by nslater** [wooorm/alex#62]
sane is the inverse of "insane" and is thus ableist in many contexts

**Comment by wooorm** [comment]
Hey @nslater!

Thanks for the issue. :smile:

*   What considerate alternatives would you suggest, instead of “sane”?
*   Would you be interested in creating a PR? Basically, you’d add a new pattern to `retext-equality/script/ablist.yml`, [like so](https://github.com/wooorm/retext-equality/blob/28f166a84096c3bcf15aa57038285ef13f7d6603/script/ablist.yml#L4-L10), and then (after `npm install`) execute `npm run build` to update the distribution files.

**Comment by wooorm** [comment]
@nslater Ping!

**Comment by wooorm** [comment]
Closing due to no response.
