### ISSUE TITLE
Suggestion: `islamist`

### ISSUE THREAD

**Issue by namagic** [wooorm/alex#90]
Islamist is casually thrown around now, and even if not used in a derogatory sense, as a Muslim, I do feel like their is generally negative connotation surrounding the word. I think the news has helped push the word to it's current nonchalantness. 

Their is a relatively recent effort by CAIR to scrub the word from the media: http://www.clarionproject.org/analysis/cair-makes-new-push-get-media-scrub-word-islamist

Even if the word isn't considered profane, I think providing a quick bio to it's potential offensiveness would be great!

**Comment by wooorm** [comment]
Great suggestion! 🎉 

1) What do you suggest instead?
2) You can add a pattern yourself through a PR in [`wooorm/retext-equality`](https://github.com/wooorm/retext-equality#contributing).

**Comment by yoshuawuyts** [comment]
perhaps muslim / muslim person / person of the islamic faith would work? idk, just dumping suggestions

**Comment by wooorm** [comment]
@yoshuawuyts 👍

Regarding `muslim person`, I believe “person” there is redundant (think ATM Machine) as `muslim` already refers to a person (wikipedia definition: “Muslim [...] relates to a person who follows the religion of Islam”).

`muslim` and `person of Islamic faith` are great!

**Comment by yoshuawuyts** [comment]
hah yeah, the reason why I emphasized the "person" in there is because I feel the word "muslim" has been twisted by media to depict these devilish creatures which are only capable of bad things. Emphasizing they're people might act as a gentle reminder that 1.6 billion muslims are just as human as the 5.4 billion non-muslims. But you're right hah
